CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payment_target_type ENUM('quote','direct_request') NOT NULL,
  payment_target_id INT NOT NULL,
  client_user_id INT NOT NULL,
  provider_user_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'PEN',
  provider_name VARCHAR(160) NOT NULL,
  description VARCHAR(255) NOT NULL,
  payment_method VARCHAR(40) NOT NULL,
  status ENUM('pending','paid','failed') NOT NULL DEFAULT 'pending',
  culqi_charge_id VARCHAR(80) NULL,
  culqi_source_id VARCHAR(80) NULL,
  culqi_response_json LONGTEXT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_payment_target (payment_target_type, payment_target_id),
  KEY idx_payments_client (client_user_id),
  KEY idx_payments_provider (provider_user_id),
  CONSTRAINT fk_payments_client FOREIGN KEY (client_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_provider FOREIGN KEY (provider_user_id) REFERENCES users(id) ON DELETE CASCADE
);
